### ISSUE TITLE
Multi concept combination

### ISSUE THREAD

**Issue by wj7486** [Rbrq03/ClassDiffusion#11]
I want to know if multiple concepts are trained simultaneously using shared KV weights or if each concept has its own KV weight (like in Customs Diffusion). I would be extremely grateful if I could receive a response from the author. thank you.

**Comment by Rbrq03** [comment]
Hey @wj7486, Thanks for your interest.

It's the custom-diffusion-style one.

**Comment by wj7486** [comment]
> Hey @wj7486, Thanks for your interest.
> 
> It's the custom-diffusion-style one.
![image](https://github.com/user-attachments/assets/312b9497-e50a-455d-a404-62382a036fa7)
![image](https://github.com/user-attachments/assets/66fba9df-ef48-44c3-82ab-79f3264976df)

Thank you for your reply, so in this multi concept combination, only different token markers were used, right？

**Comment by Rbrq03** [comment]
Yes, sorry I am not really sure about some details about custom diffusion now, but I may believe they have different text embeddings for different concepts, and a share KV weight in U-Net.

**Comment by wj7486** [comment]
> Yes, sorry I am not really sure about some details about custom diffusion now, but I may believe they have different text embeddings for different concepts, and a share KV weight in U-Net.

Thank you very much for your reply

**Comment by Rbrq03** [comment]
Please feel free to reach if you have further questions about our work.
