### ISSUE TITLE
DINO-I

### ISSUE THREAD

**Issue by wj7486** [Rbrq03/ClassDiffusion#12]
Hello, do you have a specific reference code for the indicator dino-i? The similarity between the real images I calculated is above 0.9, and I am looking forward to your reply

**Comment by Rbrq03** [comment]
I update it in

**Comment by Rbrq03** [comment]
I put an example in `utils/dinoi.py`, let me know if you have further question.

**Comment by wj7486** [comment]
> I put an example in `utils/dinoi.py`, let me know if you have further question.

Thank you very much!

**Comment by x2x5** [comment]
> I put an example in `utils/dinoi.py`, let me know if you have further question.

Hi, I didn't find utils/dinoi.py. Is it still available? thank you~
