### ISSUE TITLE
clash_start.sh didnt exist

### ISSUE THREAD

**Issue by pribadihcr** [Rbrq03/ClassDiffusion#5]
Hi, I got the following error:
```
bash: /opt/data/private/hjn/Start_scripts/clash_start.sh: No such file or directory

```

**Comment by Rbrq03** [comment]
I have fixed this bug, it occurs as some unrelated code. Try to git the updated code!

**Comment by Rbrq03** [comment]
Close as it's stable. Feel free for anyone to reopen it if the same issue occurs.
