### ISSUE TITLE
could you share the pretain ckpt？

### ISSUE THREAD

**Issue by sunzhe09** [Rbrq03/ClassDiffusion#7]

**Comment by Rbrq03** [comment]
Hello @sunzhe09 thanks for interest.
Which concept are u interested in ? And what are u want to use the pretrained ckpt for?

**Comment by sunzhe09** [comment]
I want to test my custom images，just combine the two image‘s subject。if it work ，I will make my ads picture，thx

**Comment by Rbrq03** [comment]
Hello @sunzhe09 , glad to hear that you are using our work! 
If you want to test your custom images, maybe you should train your own ckpt in custom images. I am not sure what do you mean by “pretain ckpt” (If it refers to the SD weights, you can run the train code and it will be downloaded automatically. ) , if you’re interested in the ckpt of concepts in data, just tell me and I am glad to share that.
Reach out if you have further questions!

**Comment by sunzhe09** [comment]
I just want to test this code：
import torch
from diffusers import DiffusionPipeline

pipeline = DiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16).to("cuda")
pipeline.unet.load_attn_procs("path-to-save-model", weight_name="pytorch_custom_diffusion_weights.bin")
pipeline.load_textual_inversion("path-to-save-model", weight_name="<new1>.bin")
pipeline.load_textual_inversion("path-to-save-model", weight_name="<new2>.bin")

image = pipeline(
    "a <new1> teddy bear sitting in front of a <new2> barn",
    num_inference_steps=100,
    guidance_scale=6.0,
    eta=1.0,
).images[0]
image.save("multi-subject.png")

but I can’t get path-to-save-model。it is appreciated if you could  share the bin or gradio demo

**Comment by Rbrq03** [comment]
Hi @sunzhe09 , I see.

- if you have trained the model with our code, you will find all the weight in `ckpt/${CLS_TOKEN1}_${CLS_TOKEN2}`. You can use it as the path-to-save-model
- If you just want to test the code. You can use the following [ckpt](https://drive.google.com/drive/folders/1VQTvszl2FqKhc-9YaKsRTRV3qlhmOqK4?usp=drive_link). Also I have updated it in README.

btw, I share a result generated by this ckpt.
![multi-subject](https://github.com/Rbrq03/ClassDiffusion/assets/115004993/ca574e69-934c-42a6-b46b-ae7e6c912dac)


If you have further questions, feel free to comment.
