### ISSUE TITLE
Quantitative Experiments

### ISSUE THREAD

**Issue by wj7486** [Rbrq03/ClassDiffusion#9]
![image](https://github.com/user-attachments/assets/34c11b7c-27e2-4faf-8cfd-08a6ea16ba6f)
Hello author, I would like to know if sampling 20 images per prompt in quantitative experiments refers to sampling one image per concept?
thank you.

**Comment by Rbrq03** [comment]
Hi, @wj7486. Thanks for your interest in our work.

Actually, for **each** prompt and **each** concept, we sample 20 images and then calculate the average of metrics as our final results. It means that for each model, we sampled 20 * 25 * 20 = 10000 images.

Feel free to reach me via GitHub and email if you have further questions about our work!

**Comment by wj7486** [comment]
> Hi, @wj7486. Thanks for your interest in our work.
> 
> Actually, for **each** prompt and **each** concept, we sample 20 images and then calculate the average of metrics as our final results. It means that for each model, we sampled 20 * 25 * 20 = 10000 images.
> 
> Feel free to reach me via GitHub and email if you have further questions about our work!

Thank you very much for your reply. I understand now
